"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Event = exports.emit = exports.offall = exports.off = exports.once = exports.on = exports.setResourceList = exports.Resource = exports.LoadingBar = exports.FrameAnimation = exports.Image = exports.Group = exports.MainGame = void 0;
var main_game_1 = require("./src/canvas-2d/main-game");
exports.MainGame = main_game_1.default;
var group_1 = require("./src/canvas-2d/group");
exports.Group = group_1.default;
var image_1 = require("./src/canvas-2d/image");
exports.Image = image_1.default;
var frame_animation_1 = require("./src/canvas-2d/frame-animation");
exports.FrameAnimation = frame_animation_1.default;
var loading_bar_1 = require("./src/canvas-2d/loading-bar");
exports.LoadingBar = loading_bar_1.default;
var resource_1 = require("./src/canvas-2d/resource");
exports.Resource = resource_1.default;
var resource_2 = require("./src/canvas-2d/resource");
Object.defineProperty(exports, "setResourceList", { enumerable: true, get: function () { return resource_2.setResourceList; } });
var data_structure_1 = require("./src/canvas-2d/data-structure");
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return data_structure_1.Event; } });
var event_listener_1 = require("./src/event-listener");
exports.on = event_listener_1.default;
var event_listener_2 = require("./src/event-listener");
exports.once = event_listener_2.default;
var event_listener_3 = require("./src/event-listener");
exports.off = event_listener_3.default;
var event_listener_4 = require("./src/event-listener");
exports.offall = event_listener_4.default;
var event_listener_5 = require("./src/event-listener");
exports.emit = event_listener_5.default;
